### ISSUE TITLE
Centralized asset versioning

### ISSUE THREAD

**Issue by boonebgorges** [openlab-at-city-tech/openlab-portfolio#1]
Hi @Mamaduka - Small suggestion. You've hardcoded version strings for enqueued assets - see eg https://github.com/livinglab/openlab-portfolio/blob/12a60dbc42eafc6c1d3b2049a36af5154b1702ac/src/Share/Service.php#L162. This means that we need to remember to change the strings in order to ensure cache busting. I always forget to do this this :) 

For other commons-in-a-box projects I've opted for a single version string used throughout the plugin in question whenever enqueuing first-party scripts or styles. (Third-party libraries, I think it's OK to have a hardcoded version string.) See an example at https://github.com/cuny-academic-commons/cbox-openlab-core/blob/3485da37b7d5a7d3d771a975b2b49a169c8c32d8/includes/admin.php#L85, with function definition at https://github.com/cuny-academic-commons/cbox-openlab-core/blob/3485da37b7d5a7d3d771a975b2b49a169c8c32d8/includes/functions.php#L7. I then have a build step that auto-increments this version number, which means that even during development I don't need to remember to bust the cache. https://github.com/cuny-academic-commons/cbox-openlab-core/blob/3485da37b7d5a7d3d771a975b2b49a169c8c32d8/Gruntfile.js#L61

You don't have to do exactly this - and in fact you don't have to do any of this if you think it's a bad idea! - but it's something I thought of when reading through the codebase.

**Comment by Mamaduka** [comment]
@boonebgorges I think using `cboxol_get_asset_version()` function will be better option here. Our plugin depends on CBOXOL anyways.

**Comment by Mamaduka** [comment]
@boonebgorges the changes. I think we can tag the first release and add the plugin to CBOX.

**Comment by boonebgorges** [comment]
Thanks, @Mamaduka. I'm fine with this approach, but note that we will need a polyfill if we plan to use the version of `openlab-portfolio` in this repo on the OpenLab.

Now that I think of it, there are probably a few other small changes necessary to make this version of openlab-portfolio work for the OpenLab. In particular, some of the language changes that you've made will need to be filterable - we can use a language pack for certain aspects (like simply adding the word 'OpenLab') but we will need more dynamic filtering for things like adding strings with links (like the one about "click here for help" that we removed for i18n). This could all perhaps be done with a `gettext` filter on OpenLab, instead of adding a bunch of random filters to the current plugin. What do you think?

**Comment by Mamaduka** [comment]
I case of "click here for help" we can make whole `$script_data` [messages](https://github.com/livinglab/openlab-portfolio/blob/master/src/Import/Service.php#L103) filterable.

As for removing "OpenLab" from some stings (two I think). We might want to check this with the OpenLab team. A general copy of the texts uses Portfolio.

`gettext` filters can get expensive IMO.

Do we need to provide polyfills for other `cboxol_` function as well?

**Comment by boonebgorges** [comment]
> gettext filters can get expensive IMO.

Agreed, I think they're terrible. But they're available as a fallback if needed :)

> Do we need to provide polyfills for other cboxol_ function as well?

Yes, any of them that we don't have on the OpenLab. (which is probably all of them)

**Comment by boonebgorges** [comment]
I mean, any of them that are actually used in this plugin. No need to polyfill everything :)

**Comment by Mamaduka** [comment]
Sounds good.

**Comment by Mamaduka** [comment]
Hi @boonebgorges,

Should I close this one out and prepare the first release so we can add it to CBOX?

**Comment by boonebgorges** [comment]
Yup, sounds good to me. Thanks!
