### ISSUE TITLE
More i18n and language fixes

### ISSUE THREAD

**Issue by boonebgorges** [openlab-at-city-tech/openlab-portfolio#2]
A couple of missing i18n wrappers I've come across:

https://github.com/livinglab/openlab-portfolio/blob/12a60dbc42eafc6c1d3b2049a36af5154b1702ac/src/Share/Service.php#L348

https://github.com/livinglab/openlab-portfolio/blob/12a60dbc42eafc6c1d3b2049a36af5154b1702ac/src/Import/Service.php#L107 - here we should remove the link and the reference to the OpenLab, and just say "contact network admin' or something generic like that

https://github.com/livinglab/openlab-portfolio/blob/12a60dbc42eafc6c1d3b2049a36af5154b1702ac/views/export/export.php#L6 Not sure how to make this fully generalized, but for now let's remove 'OpenLab'

https://github.com/livinglab/openlab-portfolio/blob/12a60dbc42eafc6c1d3b2049a36af5154b1702ac/views/import/header.php#L2 - ditto

https://github.com/livinglab/openlab-portfolio/blob/12a60dbc42eafc6c1d3b2049a36af5154b1702ac/views/share/dialog.php#L41

https://github.com/livinglab/openlab-portfolio/blob/12a60dbc42eafc6c1d3b2049a36af5154b1702ac/views/share/dialog.php#L6

**Comment by Mamaduka** [comment]
@boonebgorges pushed updates.

**Comment by boonebgorges** [comment]
Thanks! I think this looks good.
