### ISSUE TITLE
Improved checks for portfolio group type

### ISSUE THREAD

**Issue by boonebgorges** [openlab-at-city-tech/openlab-portfolio#3]
Sorry not to have realized this before, but unfortunately checks like this will not work:

https://github.com/livinglab/openlab-portfolio/blob/12a60dbc42eafc6c1d3b2049a36af5154b1702ac/src/Export/Service.php#L31

For one thing, this function https://github.com/cuny-academic-commons/cbox-openlab-core/commit/3485da37b7d5a7d3d771a975b2b49a169c8c32d8#diff-d08da465f856b66b1b6c32a68586d955R63 will return a `\CBOX\OL\GroupType`, not a string. See https://github.com/cuny-academic-commons/cbox-openlab-core/blob/3485da37b7d5a7d3d771a975b2b49a169c8c32d8/includes/group-types.php#L228.

More importantly, there's no guarantee that the group type in question will be called 'portfolio' on a given CBOX-OL installation, due to non-English language or whatever. Instead, we have to use the `get_is_portfolio()` method on the `GroupType` object. I have a wrapper function for it: https://github.com/cuny-academic-commons/cbox-openlab-core/blob/3485da37b7d5a7d3d771a975b2b49a169c8c32d8/includes/group-types.php#L47

**Comment by Mamaduka** [comment]
@boonebgorges updated checks for Import/Export feature.

"Add to Portfolio" probably will require a logic update as well. Logic is initialized based on the `$type` and `switch` statement.

`GroupType` has only two methods for checking the type, `::get_is_course` and `::get_is_portfolio`. Should I remove support for 'club' and 'projects'? Are these group types supported in CBOX-OL plugin?

**Comment by boonebgorges** [comment]
> "Add to Portfolio" probably will require a logic update as well. Logic is initialized based on the $type and switch statement.

Yes. Can you look at 95ac6f3 to see if it looks right to you?

> GroupType has only two methods for checking the type, ::get_is_course and ::get_is_portfolio. Should I remove support for 'club' and 'projects'? Are these group types supported in CBOX-OL plugin?

The backstory here is that the OpenLab has four hardcoded group types, and for CBOX-OL we needed to make this system more flexible, so that a network admin can decide to have more or fewer group types, or to invent their own. The default "Clubs" and "Projects" are "vanilla" group types - they represent the default behavior of group types in CBOX-OL. But there's a number of cases throughout the OpenLab (and thus CBOX-OL) where we needed certain group types to have specific abilities. Where possible, I broke these into functionality-specific flags: see `get_can_be_cloned()`, `get_supports_additional_faculty()`, etc. However, there were some cases where I didn't have the time (or we didn't have the technical and UX design resources) to figure out how the functionality check could be broken out. So I added two flags to group types: `is_portfolio()` and `is_course()` - and these are used in a few places to support features like this one. Ideally, over time, we'd remove all of these instances and turn them into feature flags. (Sorry it's a mess - your help with this would be welcome, if you see places where the work can easily be done.)

See https://github.com/cuny-academic-commons/cbox-openlab-core/blob/3485da37b7d5a7d3d771a975b2b49a169c8c32d8/classes/Install.php#L171 for the definition of default group types, which might be helpful for understanding.

So, to answer your question: 'clubs' and 'projects' are among the default group types in CBOX-OL, but they don't have any special abilities, so there are no methods specific to them.

**Comment by Mamaduka** [comment]
Thanks @boonebgorges, 95ac6f3 will do the trick.

Is there a specific issue for converting `is_portfolio()` and `'is_course()` check into feature flags? Happy to help there once we release the initial version of this plugin.

**Comment by boonebgorges** [comment]
Cool - let's mark this ticket resolved.

I just created an issue to discuss the feature-flag improvements: https://github.com/cuny-academic-commons/commons-in-a-box/issues/204

**Comment by Mamaduka** [comment]
Sounds good. Closing this one.
